# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Friendly Error Fellowship
#email: foo@example.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog for <a href="http://twitter.com/iamjessklein">Jess Klein</a> and <a href="http://portfolio.toolness.org/">Atul Varma</a>'s 2016 Processing Foundation Fellowship.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://processing.toolness.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
